### ISSUE TITLE
Color Regular Expression

### ISSUE THREAD

**Issue by featherstonej** [tmoreno/open-log-viewer#10]
I am trying to customize the colors for different log messages, and I can't seem to figure out the proper regular expression to get a match. I have tested my expression on https://regexr.com/ and it works there, but it does not work in Open Log Viewer. On the above site the following regex works [0-9-: ]{20}(ERROR) to match this string 2020-03-01 07:46:25 ERROR. What format does the regular expression need to be in for it to work?

**Comment by tmoreno** [comment]
Hi,

I've just published a new release with your issue solved.

I wasn't using regular expressions in first releases because they are a bit slow but I moved to ace editor some releases ago and it seems that the app can open the same file in the same time.

https://github.com/tmoreno/open-log-viewer/releases/1.3.0
